#include <exception>

int main () { throw std::exception(); }
